suites:
  main:
    namespace: App
    psr4_prefix: App
    src_path: app
extensions:
  PhpSpec\Laravel\Extension\LaravelExtension:
    testing_environment: "testing"
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - php
    output:
      php: coverage/spec.cov
    whitelist:
      - app
formatter.name: pretty
