language: php

php:
  - '7.2'

env:
  global:
    - APP_KEY=base64:Z++HhObkg1plehwZlK6RGSRVi4uWPiUGRYFoDOt2/Ig=
    - DB_CONNECTION=sqlite
    - DB_DATABASE="/tmp/acdc.sqlite"
    - LOG_CHANNEL=errorlog
    - APP_ENV=testing
    
install: composer install --prefer-source

# Some test setup.
before_script:
  - mkdir coverage
  - touch /tmp/acdc.sqlite
  - ./artisan migrate

script:
  # Spec tests.
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpcov merge --clover=clover.xml coverage/
  - bash <(curl -s https://codecov.io/bash) -c -F spec
  # Unit tests
  - ./vendor/bin/phpunit --testsuite Unit --coverage-php=coverage/unit.cov
  - ./vendor/bin/phpcov merge --clover=clover.xml coverage/
  - bash <(curl -s https://codecov.io/bash) -c -F unit
  # Feature tests
  - ./vendor/bin/phpunit --testsuite Feature --coverage-php=coverage/feature.cov
  - ./vendor/bin/phpcov merge --clover=clover.xml coverage/
  - bash <(curl -s https://codecov.io/bash) -c -F feature
